config/routes.rb
Rails.application.routes.draw do

  root to: 'accounts#new'

  resources :accounts do
    collection do
      post 'search'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def Index

  end

  def new
    @accounts = Account.new
  end
  
  def search
    @accounts = Account.where("name LIKE ?", "%#{new_params[:name]}%")
    sleep(2)
    respond_to do |format|
      format.js
    end
  end


  private

  def new_params
    params.require(:account).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/Index.html.erb
<h1>Accounts#Index</h1>
<p>Find me in app/views/accounts/Index.html.erb</p>

app/views/accounts/_accounts.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Account Name</th>
      <th scope="col">Country</th>
	    <th scope="col"> State</th>

    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |acct,v| %>
      <tr>
        <td scope="row"><%=acct.name%></td> 
        <td scope="row"><%=acct.country%></td> 
        <td scope="row"><%=acct.state%></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<h1 class="text-info">Find Accounts</h1>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
<%= form_for( @accounts, url: search_accounts_path, method: :post, remote: true ) do |f| %>

    <div class="form-group">
            <%= label_tag(:name, 'Account Name') %>
            <%= f.text_field :name, required: true%>
    </div>   
		
    <div class="form-group form-check"> 
        <div class="actions" class="btn btn-info">
            <%= f.submit("Search") %>
        </div>
	</div>

<% end %>

</div>

<!-- List will added as child --> 
<div id="accounts-details"></div>

<script type="text/javascript">


const domLoaded = () => {

  const searchButton = document.getElementById('new_account');
  const accountsDiv = document.getElementById('accounts-details');
  const modal = document.getElementById('myModal');

  const displayModal = (e) => {
    //e.preventDefault();
    modal.style.display =  'block' ;
  }
  const hideModal = (e) => {
    modal.style.display = 'none';
  }

searchButton.addEventListener('submit', displayModal);
  //accountsDiv.addEventListener('DOMNodeInserted', hideModal); //old fashion

//----------------Observer-------------------------------
  const callback = mutations => {
    mutations.forEach( (e) => {
            if (e.type === 'childList' ) {
              hideModal();
            };
    }); 
  };
  
  const config = {
    attributes: true,
    subtree: true,
    childList: true
  };

  const observer = new MutationObserver(callback);
  observer.observe(accountsDiv, config);
//observer.disconnect();

  }

  window.addEventListener('DOMContentLoaded', domLoaded)

</script>

app/views/accounts/search.js.erb
$("#accounts-details").html("<%= j render partial: 'accounts', locals: { accounts: @accounts } %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxRailsJs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
  </head>

  <body>
    <div class="container-md">
        <%= yield %>

    <div id="myModal" class="modal">
      <div class="text-center">
        <div class="spinner-border" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>

  </div>
</div>

    </div>


  </body>
</html>